# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowsSetupView.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TabWidgetProjects(object):
    def setupUi(self, TabWidgetProjects):
        TabWidgetProjects.setObjectName("TabWidgetProjects")
        TabWidgetProjects.resize(662, 528)
        self.Project = QtWidgets.QWidget()
        self.Project.setObjectName("Project")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Project)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_info_network_2 = QtWidgets.QLabel(self.Project)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_info_network_2.setFont(font)
        self.label_info_network_2.setText("")
        self.label_info_network_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_info_network_2.setPixmap(QtGui.QPixmap("BatchLightUE4/Resources/info.png"))
        self.label_info_network_2.setScaledContents(False)
        self.label_info_network_2.setWordWrap(False)
        self.label_info_network_2.setObjectName("label_info_network_2")
        self.horizontalLayout_4.addWidget(self.label_info_network_2)
        self.label_15 = QtWidgets.QLabel(self.Project)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_15.setFont(font)
        self.label_15.setIndent(6)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.line_header = QtWidgets.QFrame(self.Project)
        self.line_header.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_header.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_header.setObjectName("line_header")
        self.gridLayout_3.addWidget(self.line_header, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.Project)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushPathOpenUnreal = QtWidgets.QPushButton(self.groupBox)
        self.pushPathOpenUnreal.setObjectName("pushPathOpenUnreal")
        self.gridLayout_2.addWidget(self.pushPathOpenUnreal, 0, 2, 1, 1)
        self.lineEditSubfolder = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditSubfolder.setObjectName("lineEditSubfolder")
        self.gridLayout_2.addWidget(self.lineEditSubfolder, 2, 1, 1, 1)
        self.lineEditUnreal = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditUnreal.setObjectName("lineEditUnreal")
        self.gridLayout_2.addWidget(self.lineEditUnreal, 0, 1, 1, 1)
        self.label_project_file = QtWidgets.QLabel(self.groupBox)
        self.label_project_file.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_project_file.setObjectName("label_project_file")
        self.gridLayout_2.addWidget(self.label_project_file, 1, 0, 1, 1)
        self.lineEditProject = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditProject.setObjectName("lineEditProject")
        self.gridLayout_2.addWidget(self.lineEditProject, 1, 1, 1, 1)
        self.label_editor = QtWidgets.QLabel(self.groupBox)
        self.label_editor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_editor.setObjectName("label_editor")
        self.gridLayout_2.addWidget(self.label_editor, 0, 0, 1, 1)
        self.label_sub_folder = QtWidgets.QLabel(self.groupBox)
        self.label_sub_folder.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_sub_folder.setObjectName("label_sub_folder")
        self.gridLayout_2.addWidget(self.label_sub_folder, 2, 0, 1, 1)
        self.pushPathOpenProject = QtWidgets.QPushButton(self.groupBox)
        self.pushPathOpenProject.setObjectName("pushPathOpenProject")
        self.gridLayout_2.addWidget(self.pushPathOpenProject, 1, 2, 1, 1)
        self.label_project_name = QtWidgets.QLabel(self.groupBox)
        self.label_project_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_project_name.setObjectName("label_project_name")
        self.gridLayout_2.addWidget(self.label_project_name, 3, 0, 1, 1)
        self.lineEditProjectName = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditProjectName.setEnabled(False)
        self.lineEditProjectName.setObjectName("lineEditProjectName")
        self.gridLayout_2.addWidget(self.lineEditProjectName, 3, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.Project)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 3, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.Project)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeViewLevels = QtWidgets.QTreeView(self.groupBox_2)
        self.treeViewLevels.setObjectName("treeViewLevels")
        self.horizontalLayout.addWidget(self.treeViewLevels)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.gridLayout_3.addWidget(self.groupBox_2, 4, 0, 1, 1)
        self.buttonBoxProjects = QtWidgets.QDialogButtonBox(self.Project)
        self.buttonBoxProjects.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Open|QtWidgets.QDialogButtonBox.RestoreDefaults|QtWidgets.QDialogButtonBox.Save)
        self.buttonBoxProjects.setObjectName("buttonBoxProjects")
        self.gridLayout_3.addWidget(self.buttonBoxProjects, 5, 0, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("BatchLightUE4/Resources/package.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TabWidgetProjects.addTab(self.Project, icon, "")
        self.Network = QtWidgets.QWidget()
        self.Network.setObjectName("Network")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Network)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_info_network = QtWidgets.QLabel(self.Network)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_info_network.setFont(font)
        self.label_info_network.setText("")
        self.label_info_network.setTextFormat(QtCore.Qt.AutoText)
        self.label_info_network.setPixmap(QtGui.QPixmap("BatchLightUE4/Resources/info.png"))
        self.label_info_network.setScaledContents(False)
        self.label_info_network.setWordWrap(False)
        self.label_info_network.setObjectName("label_info_network")
        self.horizontalLayout_2.addWidget(self.label_info_network)
        self.label_12 = QtWidgets.QLabel(self.Network)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_12.setFont(font)
        self.label_12.setIndent(6)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_7.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.Network)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_7.addWidget(self.line_2, 1, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.Network)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.Network)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 1, 1, 1)
        self.label_network_test = QtWidgets.QLabel(self.Network)
        self.label_network_test.setEnabled(False)
        self.label_network_test.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_network_test.setObjectName("label_network_test")
        self.gridLayout_4.addWidget(self.label_network_test, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_4, 2, 0, 1, 1)
        self.buttonBoxNetwork = QtWidgets.QDialogButtonBox(self.Network)
        self.buttonBoxNetwork.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Open|QtWidgets.QDialogButtonBox.RestoreDefaults|QtWidgets.QDialogButtonBox.Save)
        self.buttonBoxNetwork.setObjectName("buttonBoxNetwork")
        self.gridLayout_7.addWidget(self.buttonBoxNetwork, 3, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("BatchLightUE4/Resources/globe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TabWidgetProjects.addTab(self.Network, icon1, "")
        self.CSV = QtWidgets.QWidget()
        self.CSV.setObjectName("CSV")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.CSV)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_info_csv = QtWidgets.QLabel(self.CSV)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_info_csv.setFont(font)
        self.label_info_csv.setText("")
        self.label_info_csv.setTextFormat(QtCore.Qt.AutoText)
        self.label_info_csv.setPixmap(QtGui.QPixmap("BatchLightUE4/Resources/info.png"))
        self.label_info_csv.setScaledContents(False)
        self.label_info_csv.setWordWrap(False)
        self.label_info_csv.setIndent(6)
        self.label_info_csv.setObjectName("label_info_csv")
        self.horizontalLayout_3.addWidget(self.label_info_csv)
        self.label_16 = QtWidgets.QLabel(self.CSV)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_16.setFont(font)
        self.label_16.setIndent(6)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_3.addWidget(self.label_16)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 0, 0, 1, 2)
        self.line_3 = QtWidgets.QFrame(self.CSV)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_5.addWidget(self.line_3, 1, 0, 2, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.csv_label_enable = QtWidgets.QLabel(self.CSV)
        self.csv_label_enable.setObjectName("csv_label_enable")
        self.gridLayout.addWidget(self.csv_label_enable, 0, 0, 1, 1)
        self.csv_checkBox_enable = QtWidgets.QCheckBox(self.CSV)
        self.csv_checkBox_enable.setObjectName("csv_checkBox_enable")
        self.gridLayout.addWidget(self.csv_checkBox_enable, 0, 1, 1, 1)
        self.csv_label_password = QtWidgets.QLabel(self.CSV)
        self.csv_label_password.setEnabled(False)
        self.csv_label_password.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.csv_label_password.setObjectName("csv_label_password")
        self.gridLayout.addWidget(self.csv_label_password, 5, 0, 1, 1)
        self.csv_label_name = QtWidgets.QLabel(self.CSV)
        self.csv_label_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.csv_label_name.setObjectName("csv_label_name")
        self.gridLayout.addWidget(self.csv_label_name, 1, 0, 1, 1)
        self.csv_lineEdit_id = QtWidgets.QLineEdit(self.CSV)
        self.csv_lineEdit_id.setEnabled(False)
        self.csv_lineEdit_id.setObjectName("csv_lineEdit_id")
        self.gridLayout.addWidget(self.csv_lineEdit_id, 4, 1, 1, 1)
        self.csv_label_id = QtWidgets.QLabel(self.CSV)
        self.csv_label_id.setEnabled(False)
        self.csv_label_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.csv_label_id.setObjectName("csv_label_id")
        self.gridLayout.addWidget(self.csv_label_id, 4, 0, 1, 1)
        self.csv_comboBox = QtWidgets.QComboBox(self.CSV)
        self.csv_comboBox.setObjectName("csv_comboBox")
        self.csv_comboBox.addItem("")
        self.csv_comboBox.addItem("")
        self.csv_comboBox.addItem("")
        self.gridLayout.addWidget(self.csv_comboBox, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 6, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.csv_lineEdit_file = QtWidgets.QLineEdit(self.CSV)
        self.csv_lineEdit_file.setObjectName("csv_lineEdit_file")
        self.horizontalLayout_8.addWidget(self.csv_lineEdit_file)
        self.csv_pushButton_file = QtWidgets.QPushButton(self.CSV)
        self.csv_pushButton_file.setObjectName("csv_pushButton_file")
        self.horizontalLayout_8.addWidget(self.csv_pushButton_file)
        self.gridLayout.addLayout(self.horizontalLayout_8, 2, 1, 1, 1)
        self.csv_lineEdit_password = QtWidgets.QLineEdit(self.CSV)
        self.csv_lineEdit_password.setEnabled(False)
        self.csv_lineEdit_password.setObjectName("csv_lineEdit_password")
        self.gridLayout.addWidget(self.csv_lineEdit_password, 5, 1, 1, 1)
        self.csv_label_file = QtWidgets.QLabel(self.CSV)
        self.csv_label_file.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.csv_label_file.setObjectName("csv_label_file")
        self.gridLayout.addWidget(self.csv_label_file, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 3, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 2, 1, 1, 1)
        self.buttonBoxCSV = QtWidgets.QDialogButtonBox(self.CSV)
        self.buttonBoxCSV.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Open|QtWidgets.QDialogButtonBox.RestoreDefaults|QtWidgets.QDialogButtonBox.Save)
        self.buttonBoxCSV.setCenterButtons(False)
        self.buttonBoxCSV.setObjectName("buttonBoxCSV")
        self.gridLayout_5.addWidget(self.buttonBoxCSV, 3, 0, 1, 2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("BatchLightUE4/Resources/git-branch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TabWidgetProjects.addTab(self.CSV, icon2, "")

        self.retranslateUi(TabWidgetProjects)
        QtCore.QMetaObject.connectSlotsByName(TabWidgetProjects)

    def retranslateUi(self, TabWidgetProjects):
        _translate = QtCore.QCoreApplication.translate
        TabWidgetProjects.setWindowTitle(_translate("TabWidgetProjects", "Tab Setup"))
        self.label_15.setText(_translate("TabWidgetProjects", "Define your options with this project"))
        self.groupBox.setTitle(_translate("TabWidgetProjects", "Paths option"))
        self.pushPathOpenUnreal.setText(_translate("TabWidgetProjects", "Choice File"))
        self.lineEditUnreal.setPlaceholderText(_translate("TabWidgetProjects", "UE4Editor.exe"))
        self.label_project_file.setText(_translate("TabWidgetProjects", "Unreal Project File :"))
        self.lineEditProject.setPlaceholderText(_translate("TabWidgetProjects", "Name.uproject"))
        self.label_editor.setText(_translate("TabWidgetProjects", "Unreal Engine Editor :"))
        self.label_sub_folder.setText(_translate("TabWidgetProjects", "Sub folder (optionnal) :"))
        self.pushPathOpenProject.setText(_translate("TabWidgetProjects", "Open File"))
        self.label_project_name.setText(_translate("TabWidgetProjects", "Project Name :"))
        self.lineEditProjectName.setPlaceholderText(_translate("TabWidgetProjects", "This projects contain no description and name."))
        self.groupBox_2.setTitle(_translate("TabWidgetProjects", "Levels"))
        self.label_6.setText(_translate("TabWidgetProjects", "level name"))
        TabWidgetProjects.setTabText(TabWidgetProjects.indexOf(self.Project), _translate("TabWidgetProjects", "Projects"))
        self.label_12.setText(_translate("TabWidgetProjects", "Your setup with all computer avaible on your network"))
        self.label_3.setText(_translate("TabWidgetProjects", "Network Name :"))
        self.pushButton.setText(_translate("TabWidgetProjects", "Generate file"))
        self.label_network_test.setText(_translate("TabWidgetProjects", "No Json Setup."))
        TabWidgetProjects.setTabText(TabWidgetProjects.indexOf(self.Network), _translate("TabWidgetProjects", "Network"))
        self.label_16.setText(_translate("TabWidgetProjects", "Setup your CSV software, Git, Perforce or SVN."))
        self.csv_label_enable.setText(_translate("TabWidgetProjects", "Activate the CSV Module :"))
        self.csv_checkBox_enable.setText(_translate("TabWidgetProjects", "Enable"))
        self.csv_label_password.setText(_translate("TabWidgetProjects", "Password :"))
        self.csv_label_name.setText(_translate("TabWidgetProjects", "CSV Tools :"))
        self.csv_label_id.setText(_translate("TabWidgetProjects", "Identifiant :"))
        self.csv_comboBox.setItemText(0, _translate("TabWidgetProjects", "Perforce"))
        self.csv_comboBox.setItemText(1, _translate("TabWidgetProjects", "Git"))
        self.csv_comboBox.setItemText(2, _translate("TabWidgetProjects", "Subversion"))
        self.csv_lineEdit_file.setPlaceholderText(_translate("TabWidgetProjects", "p4.exe"))
        self.csv_pushButton_file.setText(_translate("TabWidgetProjects", "Open"))
        self.csv_label_file.setText(_translate("TabWidgetProjects", "Executable File"))
        TabWidgetProjects.setTabText(TabWidgetProjects.indexOf(self.CSV), _translate("TabWidgetProjects", "CSV"))

